In [1]:
import numpy as np
import math

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# print dimension of array by ndim
print(a.ndim)

1


In [6]:
b = np.array([[1,2,3],[4,5,6,],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# print length of each list by shape
print(b.shape)

(3, 3)


In [9]:
# check the type of item in array
a.dtype

dtype('int32')

In [10]:
# float are also accepted in numpy array
c = np.array([2.2, 3.2, 4])
c.dtype.name

'float64'

In [11]:
# intial placeholder in array
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# we can also generate array with random number
np.random.rand(3,3)

array([[0.83360392, 0.10269182, 0.51834798],
       [0.93355154, 0.74858715, 0.06251335],
       [0.60797521, 0.32050293, 0.26586074]])

In [16]:
# we can create sequence of number with arange() function
# inclusive of 10 and exclusive of 50 with diff 2

f = np.arange(10, 50, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [18]:
# linspace() is used to generate float sequence with both exterimities inclusive

g = np.linspace(0,2,4)
print(g)

[0.         0.66666667 1.33333333 2.        ]
